version: '3.8'
services:
  mysqlserver:
    image: mysql:8.0
    networks:
      - employee-mysql
    container_name: mysqlserver
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_USER=petclinic
      - MYSQL_PASSWORD=petclinic
      - MYSQL_DATABASE=petclinic
    volumes:
      - mysql_data:/var/lib/mysql
      - mysql_config:/etc/mysql/conf.d

  petclinic:
    build:
      context: .
      target: development
    networks:
      - employee-mysql
    ports:
      - "8000:8000"
      - "8080:8080"
    environment:
      - SERVER_PORT=8080
      - MYSQL_URL=jdbc:mysql://mysqlserver:3306/petclinic?useSSL=false&allowPublicKeyRetrieval=true&autoReconnect=true
    volumes:
      - ./:/app
    depends_on:
      - mysqlserver

volumes:
  mysql_data:
  mysql_config:

networks:
  employee-mysql: